name: GCFE
description: Go Concurrency for Everyone.
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # provider for service locator and state management
  provider: ^4.0.4
  # value equality
  equatable: ^1.1.1
  # functional programming
  dartz: ^0.8.9
  # route transition animation
  route_transitions: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mock
  mockito: ^4.1.1

flutter:
  uses-material-design: true
